In [ ]:
import cv2
import tensorflow as tf
from tensorflow.keras.models import load_model
import numpy as np
from pygame import mixer

# New Section

In [ ]:
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_eye.xml')
model = load_model(r'C:\Users\manav\Downloads\DriverDrowsiness\models\model.h5')

In [ ]:
mixer.init()
sound= mixer.Sound(r'C:\Users\manav\Downloads\DriverDrowsiness\alarm.wav')
cap = cv2.VideoCapture(0)
Score = 0
while True:
    ret, frame = cap.read()
    height,width = frame.shape[0:2]
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    faces= face_cascade.detectMultiScale(gray, scaleFactor= 1.2, minNeighbors=3)
    eyes= eye_cascade.detectMultiScale(gray, scaleFactor= 1.2, minNeighbors=3)
    
    cv2.rectangle(frame, (0,height-50),(200,height),(0,0,0),thickness=cv2.FILLED)
    
    for (x,y,w,h) in faces:
        cv2.rectangle(frame,pt1=(x,y),pt2=(x+w,y+h), color= (255,0,0), thickness=3 )
        
    for (ex,ey,ew,eh) in eyes:
        #cv2.rectangle(frame,pt1=(ex,ey),pt2=(ex+ew,ey+eh), color= (255,0,0), thickness=3 )
        
        # preprocessing steps
        eye= frame[ey:ey+eh,ex:ex+w]
        eye= cv2.resize(eye,(80,80))
        eye= eye/255
        eye= eye.reshape(80,80,3)
        eye= np.expand_dims(eye,axis=0)
        # preprocessing is done now model prediction
        prediction = model.predict(eye)
    
        
        
            
        # if eyes are open
        if prediction[0][1]>0.90:
            cv2.putText(frame,'open',(10,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(255,255,255),
                       thickness=1,lineType=cv2.LINE_AA)      
            cv2.putText(frame,'Score'+str(Score),(100,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(255,255,255),
                       thickness=1,lineType=cv2.LINE_AA)
            Score = Score-1
            if (Score<0):
                Score=0
                
        # if eyes are closed
        else: 
            cv2.putText(frame,'closed',(10,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(255,255,255),
                       thickness=1,lineType=cv2.LINE_AA)
            cv2.putText(frame,'Score'+str(Score),(100,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(255,255,255),
                       thickness=1,lineType=cv2.LINE_AA)
            Score=Score+1
            if(Score>20):
                try:
                    sound.play()
                except:
                    pass

        
        
    cv2.imshow('frame',frame)
    if cv2.waitKey(33) & 0xFF==ord('q'):
        break
        
cap.release()
cv2.destroyAllWindows()

In [ ]:
'''cap = cv2.VideoCapture(0)
while True:
    ret, frame = cap.read()
    height,width = frame.shape[0:2]
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    faces= face_cascade.detectMultiScale(gray, scaleFactor= 1.2, minNeighbors=3)
    eyes= eye_cascade.detectMultiScale(gray, scaleFactor= 1.2, minNeighbors=3)

    for (x,y,w,h) in faces:
        cv2.rectangle(frame,pt1=(x,y),pt2=(x+w,y+h), color= (255,0,0), thickness=3 )
        
    for (ex,ey,ew,eh) in eyes:
        #cv2.rectangle(frame,pt1=(ex,ey),pt2=(ex+ew,ey+eh), color= (255,0,0), thickness=3 )
        
        # preprocessing steps
        eye= frame[ey:ey+eh,ex:ex+w]
        eye= cv2.resize(eye,(80,80))
        eye= eye/255
        eye= eye.reshape(80,80,3)
        eye= np.expand_dims(eye,axis=0)
        # preprocessing is done now model prediction
        prediction = model.predict(eye)
        print(prediction)
        
        cv2.imshow('frame',frame)
        if cv2.waitKey(33) & 0xFF==ord('q'):
            break
        
cap.release()
cv2.destroyAllWindows()'''

[[9.9919564e-01 8.0441975e-04]]
[[0.6357281 0.3642719]]
[[0.783825   0.21617502]]
[[0.9965132 0.0034868]]
[[9.9958104e-01 4.1902013e-04]]
[[9.9999940e-01 5.6861853e-07]]
[[0.5857034 0.4142966]]
[[0.2029372 0.7970628]]
[[1.2134595e-04 9.9987864e-01]]
[[9.9998045e-01 1.9585861e-05]]
[[9.9999881e-01 1.2291023e-06]]
[[0.616242 0.383758]]
[[1.9165303e-04 9.9980837e-01]]
[[0.0013327  0.99866736]]
[[0.2751744  0.72482556]]
[[0.98918194 0.01081806]]
[[9.9974722e-01 2.5273432e-04]]
[[0.9921361  0.00786388]]
[[0.00122212 0.9987779 ]]
[[0.98195535 0.01804465]]
[[0.9287     0.07129997]]
[[0.98697364 0.01302632]]
[[0.8715898  0.12841019]]
[[0.9968899  0.00311012]]
[[0.97416186 0.02583815]]
[[0.799941   0.20005894]]
[[0.99480295 0.00519702]]


KeyboardInterrupt: 